# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
apis/v1/xkcd-orig.yaml:
  info-license:
    - '#/info'
  no-server-trailing-slash:
    - '#/servers/0/url'
  operation-operationId:
    - '#/paths/~1info.0.json/get/operationId'
    - '#/paths/~1{comicId}~1info.0.json/get/operationId'
  operation-summary:
    - '#/paths/~1info.0.json/get/summary'
    - '#/paths/~1{comicId}~1info.0.json/get/summary'
  operation-4xx-response:
    - '#/paths/~1info.0.json/get/responses'
    - '#/paths/~1{comicId}~1info.0.json/get/responses'
  security-defined:
    - '#/paths/~1info.0.json/get'
    - '#/paths/~1{comicId}~1info.0.json/get'
